import { useMemo, useState } from 'react'
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { assets, vulnerabilities } from './data/demoData'
import { benchmarks } from './lib/metrics'
import { scoreVulnerability } from './lib/riskEngine'
import type { PatchTest, Priority, Vulnerability } from './types'

const tierColor: Record<Priority, string> = { P0: '#ff5263', P1: '#ffae42', P2: '#3e9eff', P3: '#8f9ab3' }
const nav = ['Overview', 'Remediation queue', 'Research lab', 'Architecture'] as const

export default function App() {
  const [active, setActive] = useState<(typeof nav)[number]>('Overview')
  const [filter, setFilter] = useState<'All' | Priority>('All'); const [selectedId, setSelectedId] = useState(vulnerabilities[0].id)
  const [patches, setPatches] = useState<Record<string, PatchTest>>({})
  const scored = useMemo(() => vulnerabilities.map(v => {
    const result = scoreVulnerability(v, assets.find(a => a.id === v.assetId)!)
    const patch = patches[v.id]
    return { ...v, asset: assets.find(a => a.id === v.assetId)!, result: patch?.outcome === 'passed' ? { ...result, score: Math.max(0, result.score - patch.riskReduction), priority: result.score - patch.riskReduction >= 85 ? 'P0' as Priority : result.score - patch.riskReduction >= 70 ? 'P1' as Priority : result.score - patch.riskReduction >= 45 ? 'P2' as Priority : 'P3' as Priority } : result, patch }
  }).sort((a, b) => b.result.score - a.result.score), [patches])
  const selected = scored.find(item => item.id === selectedId) ?? scored[0]
  const filtered = filter === 'All' ? scored : scored.filter(item => item.result.priority === filter)
  const distribution = (['P0', 'P1', 'P2', 'P3'] as Priority[]).map(priority => ({ name: priority, value: scored.filter(item => item.result.priority === priority).length }))
  const patch = (vulnerability: Vulnerability) => {
    const deterministicPass = vulnerability.id.length % 2 === 0 || vulnerability.kev
    setPatches(current => ({ ...current, [vulnerability.id]: { vulnerabilityId: vulnerability.id, outcome: deterministicPass ? 'passed' : 'failed', canaryCoverage: deterministicPass ? 20 : 10, riskReduction: deterministicPass ? 42 : 0, note: deterministicPass ? '20% canary healthy; remediation applied locally.' : 'Canary regression detected; remediation held for review.' } }))
  }
  const openCount = scored.filter(item => item.status !== 'Remediated').length
  return <div className="shell">
    <aside><div className="brand"><span>◈</span> RiskCompass</div><p className="subtle">Dynamic vulnerability intelligence</p><nav>{nav.map(item => <button className={active === item ? 'nav active' : 'nav'} onClick={() => setActive(item)} key={item}>{item}</button>)}</nav><div className="sidebar-note">STATIC MVP<br/><span>Local simulation only</span></div></aside>
    <main><header><div><p className="eyebrow">SOC OPERATIONS / AUG 16, 2026</p><h1>{active}</h1></div><div className="demo-badge">● Seeded synthetic demo data</div></header>
      {active === 'Overview' && <>
        <section className="metric-grid"><Metric label="Open findings" value={openCount} hint="Across 6 assets" /><Metric label="Immediate action" value={`${distribution[0].value} P0`} hint="Prioritize today" accent="red" /><Metric label="Crown-jewel exposure" value={`${scored.filter(item => item.asset.tier === 'Crown jewel').length}`} hint="Findings mapped" accent="amber" /><Metric label="Forecasted 30-day exploit" value={`${selected.result.forecast.day30}%`} hint={selected.id} accent="blue" /></section>
        <section className="grid-two"><Panel title="Priority distribution" subtitle="Contextual Dynamic Risk"><div className="chart pie"><ResponsiveContainer><PieChart><Pie data={distribution} dataKey="value" nameKey="name" innerRadius={58} outerRadius={88}>{distribution.map(item => <Cell key={item.name} fill={tierColor[item.name as Priority]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div><div className="legend">{distribution.map(item => <div key={item.name}><span style={{ background: tierColor[item.name as Priority] }} /> {item.name} <b>{item.value}</b></div>)}</div></Panel><Panel title="Highest-risk assets" subtitle="Contextual exposure by finding"><div className="chart"><ResponsiveContainer><BarChart data={scored.map(item => ({ name: item.asset.name.split(' ')[0], score: item.result.score }))}><XAxis dataKey="name" stroke="#73809b" tickLine={false} axisLine={false}/><YAxis stroke="#73809b" tickLine={false} axisLine={false}/><Tooltip/><Bar dataKey="score" fill="#4f8cff" radius={[5,5,0,0]} /></BarChart></ResponsiveContainer></div></Panel></section>
        <section className="panel queue"><div className="panel-head"><div><h2>Remediation queue</h2><p>Ranked by contextual risk, not static severity alone.</p></div><select aria-label="Filter by priority" value={filter} onChange={event => setFilter(event.target.value as 'All' | Priority)}><option>All</option><option>P0</option><option>P1</option><option>P2</option><option>P3</option></select></div><table><thead><tr><th>Finding</th><th>Asset context</th><th>Signals</th><th>Dynamic risk</th><th>Action</th></tr></thead><tbody>{filtered.map(item => <tr className={selected.id === item.id ? 'selected' : ''} key={item.id} onClick={() => setSelectedId(item.id)}><td><b>{item.id}</b><span>{item.title}</span></td><td>{item.asset.name}<small>{item.asset.exposure} · {item.asset.tier}</small></td><td><span className="pill">EPSS {(item.epss * 100).toFixed(0)}%</span>{item.kev && <span className="kev">KEV</span>}</td><td><strong className="score" style={{ color: tierColor[item.result.priority] }}>{item.result.score}</strong><span className="priority" style={{ background: tierColor[item.result.priority] }}>{item.result.priority}</span></td><td><button className="text-button" onClick={event => { event.stopPropagation(); setSelectedId(item.id) }}>Inspect →</button></td></tr>)}</tbody></table></section>
        <section className="detail-grid"><Panel title={`${selected.id} rationale`} subtitle={selected.result.explanation}><div className="factor-list">{selected.result.contributions.sort((a,b)=>b.points-a.points).map(item => <div key={item.label}><span>{item.label}</span><div><i style={{ width: `${item.points}%` }} /></div><b>+{item.points}</b></div>)}</div></Panel><Panel title="Action simulator" subtitle="Attack path, forecast, and safe canary simulation"><div className="action-card"><p><b>Path to crown jewel:</b> {selected.result.attackPath.route.join(' → ')}</p><p><b>Monte Carlo-style breach probability:</b> {selected.result.attackPath.probability}% (+{selected.result.attackPath.adjustment} score adjustment)</p><div className="forecast">{[['30d', selected.result.forecast.day30], ['60d', selected.result.forecast.day60], ['90d', selected.result.forecast.day90]].map(([label, value]) => <div key={String(label)}><b>{value}%</b><span>{label} exploit forecast</span></div>)}</div>{selected.patch ? <p className={selected.patch.outcome === 'passed' ? 'success' : 'failure'}>{selected.patch.note}</p> : <button className="primary" onClick={() => patch(selected)}>Run 20% patch canary</button>}<p className="recommendation">{selected.recommendation}</p></div></Panel></section>
      </>}
      {active === 'Remediation queue' && <section className="panel queue standalone"><div className="panel-head"><div><h2>All findings</h2><p>Use the overview to inspect explanations and simulate patch outcomes.</p></div></div>{scored.map(item => <article className="finding" key={item.id}><span className="priority" style={{background:tierColor[item.result.priority]}}>{item.result.priority}</span><div><b>{item.id}</b><h3>{item.title}</h3><p>{item.asset.name} · {item.result.explanation}</p></div><strong className="score" style={{color:tierColor[item.result.priority]}}>{item.result.score}</strong></article>)}</section>}
      {active === 'Research lab' && <Research />}
      {active === 'Architecture' && <Architecture />}
    </main>
  </div>
}
function Metric({ label, value, hint, accent = 'default' }: { label: string; value: string | number; hint: string; accent?: string }) { return <article className={`metric ${accent}`}><p>{label}</p><h2>{value}</h2><span>{hint}</span></article> }
function Panel({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section className="panel"><div className="panel-head"><div><h2>{title}</h2><p>{subtitle}</p></div></div>{children}</section> }
function Research() { const data = benchmarks(vulnerabilities, assets); return <section className="panel research"><div className="panel-head"><div><h2>Prioritization evaluation</h2><p>Demo labels are seeded only: this is methodology illustration, not a validated ML claim.</p></div></div><div className="benchmark-table"><table><thead><tr><th>Model</th><th>Precision@5</th><th>Recall@5</th><th>F1</th><th>ROC-AUC</th><th>PR-AUC</th><th>Rank correlation</th><th>False-priority</th><th>Workload reduction</th></tr></thead><tbody>{data.map(row => <tr className={row.model === 'Dynamic Risk' ? 'dynamic' : ''} key={row.model}><td>{row.model}</td><td>{row.precisionAtK}</td><td>{row.recallAtK}</td><td>{row.f1}</td><td>{row.rocAuc}</td><td>{row.prAuc}</td><td>{row.spearman}</td><td>{(row.falsePriorityRate*100).toFixed(0)}%</td><td>{row.workloadReduction}%</td></tr>)}</tbody></table></div><div className="method"><h3>Method</h3><p>The Dynamic Risk column combines CVSS, EPSS, KEV, asset criticality, exposure, exploit availability, threat activity, vulnerability age, business impact, and a capped attack-path adjustment. Baselines intentionally omit organizational context.</p></div></section> }
function Architecture() { const roadmap = [['Threat intelligence NLP', 'Live MISP/NVD/EPSS ingestion and threat-velocity classification'], ['Federated learning', 'Privacy-preserving model-signal aggregation'], ['SOAR playbooks', 'Approved remediation workflows and analyst hand-offs'], ['Honeypots', 'Defensive decoy telemetry for model calibration'], ['Edge scoring', 'Distilled models close to on-premise assets'], ['DevSecOps gates', 'CI/CD scoring policies and pull-request checks'], ['Industry thresholds', 'Sector-aware policy profiles and reporting'], ['Immutable audit trail', 'Compliance-grade decision history']]; return <section className="panel architecture"><div className="panel-head"><div><h2>Production evolution</h2><p>These integrations are deliberately non-functional in the static GitHub Pages MVP.</p></div></div>{roadmap.map(([title, text]) => <article key={title}><div>◇</div><h3>{title}</h3><p>{text}</p><span>Roadmap</span></article>)}</section> }
